jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run test
          command: yarn test
      - run:
          name: Run test coverage and upload to coveralls
          command: yarn test:cov
      - store_artifacts:
          path: coverage
orbs:
  node: circleci/node@3.0.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
